### ISSUE TITLE
List of features for the next big release

### ISSUE THREAD

**Issue by mislav** [github/hub#1232]
Here's [what I want in hub 2.3.0](https://github.com/github/hub/milestone/2) (we could even tag it 3.0.0, considering the volume of changes):
- [x] improve `help` system by splitting into individual man pages #1087
  - [x] tweak release process to auto-build and package man pages
- [x] `release` command graduated from beta #1095
- [x] `issue` command graduated from beta #1099
  - [ ] make an equivalent command to list pull requests #1303
  - [x] add missing filtering and sorting options to issue listing #1234
  - [ ] add an option to limit the number of results
  - [ ] add ability to list issues/pulls a la Dashboard, i.e. across a whole org, or all belonging to you #1224
  - [ ] add caching locally and fetch only records updated since last cache
- [ ] improve detecting of `pull-request` head & base #461 #877 #814 #1239
  - [ ] better handling of unpushed branches #1130
  - [ ] option to auto-push changes to a remote before opening the PR #165
  - [ ] option to create the PR using the web interface #1005 #688
  - [ ] improve support for forks named differently than parent repo
- [ ] enable passing milestone title instead of number to `issue create`, `pull-request` #1089
- [x] commands that output a URL of created resource (`pull-request`, `issue create`, `release create`) should have an option to copy the URL to clipboard #1111 #182 #1264
- [x] add support for issue/PR templates #1187 #1145 #1118 #937
  - [x] add support for interactively editing a template file passed in using `-F` #924
  - [ ] prepare pull request message hook #1179 #1174
- [ ] dedicated command for authentication & configuration #225 #992
  - [ ] add system for per-command default configuration #964 #1194 #720
  - [ ] enable passing in Personal Access token, mostly for GHE users who don't have the option to authenticate using username/password
  - [ ] retire `git config --get-all hub.host` configuration
  - [ ] add global `--repo OWNER/NAME` argument that lets you perform operations a repo other than the directory you're currently in
  - [ ] add global `--host HOST` argument that changes the default `github.com` host and eliminate the interactive host picker #1184
  - [ ] add support for XDG Base Directory spec #1061
- [ ] retire `browse` command in favor of `open` command that takes one argument and automatically figures out whether it's a branch, commit, subpage, or other kind of resource to navigate to #382 #1112 #1107 #897 #782 #723 #602
- [x] reimplement `checkout` command to fetch `refs/pull/XY/head` instead of adding a git remote #1069 #1206 #1133 #1236 #1235
- [ ] improve `upstream` vs `origin` remote naming in `clone`, `fork`, etc. #798 #811 #1271
  - [ ] add `fork` option to provide custom remote name #762
  - [ ] add `fork` option to provide custom name for new repo #697
- [ ] improve `create ORG/NAME` by requesting a team name to create the repo under if necessary #431
  - [ ] optional org argument to `create`#1408
  - [x] optional org argument to `fork` #505
- [x] implement [`sync`](https://github.com/mislav/dotfiles/blob/370154a5adc482afd89606c126bcd18df2560013/bin/git-sync) command #906 #618
- [ ] new `search` command? #833
- [ ] [low-level `api`](https://github.com/mislav/go-travis/blob/8821a770c38955f796c71b8f2e19135aa65138c4/commands/api.go) command for manual API access #1407
- [ ] add option to open failing `ci-status` check in browser #449

The new `--format` option is pretty rad:

![screen shot 2016-08-16 at 6 21 37 pm](https://cloud.githubusercontent.com/assets/887/17738880/5f675842-6493-11e6-954c-2b47cf502850.png)

**Comment by DanyC97** [comment]
great work @mislav !! any rough timeline when you planning to finish release the above goodies ?

**Comment by mislav** [comment]
@DanyC97 All from the above list won't all make it to the very next release, but I'm planning to release 2.3.0 this month. Check out the existing prerelease builds in the Releases section.

**Comment by igorsantos07** [comment]
Hello there! Any plans for a new release? I just noticed I was missing the important PR template my team uses by using `hub` to create PRs on the command line... I'm on 2.3.0, and it seems that feature got merged more than a year ago 😅

**Comment by e-beach** [comment]
This is an important question. I would also like to know what changes are necessary to release a new version.

**Comment by igorsantos07** [comment]
Well, it _seems_ that feature I mentioned is indeed working; I probably used `-m` that bypassed the template. Should `hub` warn on these cases? 🤔

**Comment by mislav** [comment]
Hi everyone; thanks for your patience. My proposed feature set for 2.3.0 was overly ambitious and I've missed the schedule I have set for myself earlier this year. This is because of the two most important features for 2.3.0 (dedicated command for authentication & configuration, improving pull-request handling of head/base detection) are also the most tricky ones to implement, and I'm the only one working on hub maintenance lately.

I'm still slowly heading towards a release, and since Projects have shipped since I've opened this tracking issue, I've moved the remaining TODO items [to a new Project](https://github.com/github/hub/projects/1?fullscreen=true) so they can be tracked there. As always, you can test out the latest features by grabbing one of the prereleases from the Releases section. 

I'm gonna close this issue out in favor of the Project board. I'll be posting this thread if there are any big updates in the future.

@igorsantos07: Indeed, the `-m` flag bypasses the template, as does any other option in which you explicitly provide the text for the pull request. The template is only rendered in your text editor when there is no explicit PR subject/message provided. This is by design: we want to be able to skip the template for the purpose of automation (i.e. explicit arguments should always be taken verbatim and "win" over implicit defaults).

**Comment by timofonic** [comment]
@mislav @e-beach Has there been some progress about this?
